# Site settings
title: Zen Kyprianou
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Zen's thoughts on programming, apps, tech, and other general ramblings about
  the world we live in.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zenonas.com" # the base hostname & protocol for your site
twitter_username: zenonkyp
github_username: zenonas

# Build settings
markdown: kramdown
